pipeline {
  agent any

  environment {
    REGISTRY = "localhost:5000"
    APP_NAME = "zulip"
  }

  stages {
    stage('Checkout') {
      steps {
        git 'https://github.com/your-username/your-repo.git'
      }
    }

    stage('Build Image') {
      steps {
        dir("zulip") {
          sh """
            docker build -t ${REGISTRY}/${APP_NAME}:latest .
          """
        }
      }
    }

    stage('Push Image') {
      steps {
        sh "docker push ${REGISTRY}/${APP_NAME}:latest"
      }
    }
  }
}

